name: Deploy challenge on gke
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --all --tag
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: |
          git config --global user.email "actions@action.com"
          git config --global user.name "github-action"
          cd dockerfiles/arch-i3
          docker build -t linucks-io-arch-i3:latest .
          docker tag linucks-io-arch-i3:latest aliasrahil/linucks-io-arch-i3:latest
          docker push aliasrahil/linucks-io-arch-i3:latest
