on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: |
          cd dockerfiles/kali-gnome
          docker build -t linucks-io-kali-gnome:latest .
          docker tag linucks-io-kali-gnome:latest aliasrahil/linucks-io-kali-gnome:latest
          docker push aliasrahil/linucks-io-kali-gnome:latest
